name: build docs

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/') # only deploy pages on release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
    
      - name: Install dependencies
        run: poetry install
      
      - run: poetry run mkdocs gh-deploy --force