name: tests

on:
  workflow_dispatch:
  pull_request_target:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.11", "3.10", "3.9"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.4.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Style checking
        run: |
          poetry run ruff check src tests
          poetry run ruff format --check src tests

      - name: Type checking
        run: |
          poetry run mypy src tests

      - name: Run tests
        run: poetry run pytest
