name: tests

on:
  workflow_dispatch:
  pull_request_target:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    # avoid duplicate tests when pushing commits to PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      - name: Style checking
        run: |
          uv run ruff check src tests
          uv run ruff format --check src tests

      - name: Type checking
        run: uv run mypy src tests docs/usage/scripts

      - name: Run tests
        run: uv run pytest
